Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -27,21 +27,17 @@ jobs:
           channel: stable
           cache: true
 
-      - name: Check source file
+      - name: Check source
         run: |
-          ls -la
-
-          if [ ! -f "liyona-flutter-source-v1.4.1.zip" ]; then
-            echo "ERROR: liyona-flutter-source-v1.4.1.zip not found"
-            exit 1
-          fi
+          test -f liyona-flutter-source-v1.5.zip || \
+          (echo "liyona-flutter-source-v1.5.zip not found" && exit 1)
 
       - name: Extract source
         run: |
           rm -rf liyona-source buildapp
 
           unzip -o \
-            liyona-flutter-source-v1.4.1.zip \
+            liyona-flutter-source-v1.5.zip \
             -d liyona-source
 
           SOURCE_DIR=$(dirname "$(find liyona-source -name pubspec.yaml | head -n 1)")
@@ -109,17 +105,17 @@ jobs:
         run: |
           flutter pub get
 
-      - name: Generate app icon
+      - name: Generate icon
         working-directory: buildapp
         run: |
           dart run flutter_launcher_icons
 
-      - name: Generate splash screen
+      - name: Generate splash
         working-directory: buildapp
         run: |
           dart run flutter_native_splash:create
 
-      - name: Build release APK
+      - name: Build APK
         working-directory: buildapp
         run: |
           flutter build apk --release
@@ -128,11 +124,11 @@ jobs:
         run: |
           cp \
             buildapp/build/app/outputs/flutter-apk/app-release.apk \
-            Liyona-Shop-v1.4.1.apk
+            Liyona-Shop-v1.5.apk
 
-      - name: Upload APK artifact
+      - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
-          name: Liyona-Shop-v1.4.1-APK
-          path: Liyona-Shop-v1.4.1.apk
+          name: Liyona-Shop-v1.5-APK
+          path: Liyona-Shop-v1.5.apk
           if-no-files-found: error
